Pablo gar/audit notebook 4
chanzuckerberg/cellxgene-census pull request #377
Opened 2023-04-13 00:32 UTC by pablo-gar

Completes work for #360 

Removes notebook `census_rank_gene_groups.ipynb` as it is trivial and doesn't add significant value.

2023-04-14 11:56 UTC, ebezzi commented on api/python/notebooks/api_demo/census_compute_over_X.ipynb
> +    "This tutorial showcase computing a variety of per-gene and per-cell statistics for a user-defined query using out-of-core operations.\n",
```suggestion
    "This tutorial showcases computing a variety of per-gene and per-cell statistics for a user-defined query using out-of-core operations.\n",
```

2023-04-14 11:58 UTC, ebezzi commented on api/python/notebooks/api_demo/census_dataset_presence.ipynb
> +    "Now that we the dataset table, the genes metadata table, and the dataset presence matrix, we can check if a gene or set of genes were measured in a specific dataset.\n",
```suggestion
    "Now that we have the dataset table, the genes metadata table, and the dataset presence matrix, we can check if a gene or set of genes were measured in a specific dataset.\n",
```

2023-04-14 12:04 UTC, ebezzi approved these changes
A few comments but LGTM otherwise.

2023-04-14 12:04 UTC, ebezzi commented on api/python/notebooks/api_demo/census_datasets.ipynb
> +    "You can download the original H5AD file for any given dataset. This is the same H5AD you can download from the CELLxGENE Portal, and may contain additional data-submitter provided information wh
from `CELLxGENE Discover`? Otherwise portal should be lowercase IMHO.

2023-04-14 15:52 UTC, atolopko-czi requested changes
I found one unfinished sentence and there may be cells that are lacking output (though I may be confused by the complicated diff of the notebook changes).  Other than that, just a number of minor corrections and suggestions.

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/analysis_demo/comp_bio_explore_and_load_lung_data.ipynb
> +    "First we open the Census, if you are not familiar with the basics of the Census API you should take a look at notebook [Learning about the CZ CELLxGENE Census](https://cellxgene-census.readthedo
```suggestion
    "First, we will open the Census. If you are not familiar with the basics of the Census API you should take a look at notebook [Learning about the CZ CELLxGENE Census](https://cellxgene-census.readthedocs.io/en/latest/notebooks/analysis_demo/comp_bio_census_info.html)\n"
```

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/analysis_demo/comp_bio_explore_and_load_lung_data.ipynb
> +    "## Calculating QC metrics of the lung data.\n",
```suggestion
    "## Calculating QC metrics of the lung data\n",
```

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/api_demo/census_dataset_presence.ipynb
> +    "# Genes measured in each cell (presence matrix)\n",
```suggestion
    "# Genes measured in each cell (dataset presence matrix)\n",
```

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/api_demo/census_dataset_presence.ipynb
> +    "The Census is a compilation of cells from multiple different datasets. Not all of the source datasets measured the exact same set of genes. This notebook describes the way to identify genes meas
```suggestion
    "The Census is a compilation of cells from multiple datasets that may differ by the sets of genes they measure. This notebook describes the way to identify the genes measured per dataset.\n",
```

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/api_demo/census_dataset_presence.ipynb
> +    "The `cellxgene_census` python package contains a convenient API to open the latest version of the Census. If you open "
⚠️ Unfinished sentence?

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/api_demo/census_datasets.ipynb
> +    "# Exploring the dataset table\n",
```suggestion
    "# Exploring the Census Datasets table\n",
```

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/api_demo/census_datasets.ipynb
> +    "Each Census contains a top-level dataframe itemizing the datasets contained therein. You can read this into a `pandas.DataFrane`."
```suggestion
    "Each Census contains a top-level dataframe itemizing the datasets contained therein. You can read this into a `pandas.DataFrame`."
```

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/api_demo/census_datasets.ipynb
> +    "# Option 2: Direct download\n",
Nit: make this option 1, since it's easier and is the Census Way. :)

2023-04-14 15:52 UTC, atolopko-czi commented on api/python/notebooks/api_demo/census_query_extract.ipynb
> +    "   - Comparisons are one of column op value or column op column\n",
```suggestion
    "   - Comparisons are one of `<column> <op> <value>` or `<column> <op> <column>`\n",
```
formatting might help readability

2023-04-18 01:13 UTC, pablo-gar commented
Thanks @atolopko-czi and @ebezzi I've addressed your comments

2023-04-18 11:51 UTC, atolopko-czi approved these changes
LGTM!

2023-04-18 17:22 UTC, merged