demo notebook for HVG experimental API
chanzuckerberg/cellxgene-census pull request #536
Opened 2023-06-13 19:02 UTC by bkmartinjr

Changes:
* created experimental API notebooks folder and moved pytorch notebook into experimental API folder
* added HVG notebook to experimental folder
* cleaned up docs/notebooks symlinks (removed dead links, added missing link)
* pre-commit fixes captured in #539 

Fixes #532 
Fixes #535

*Note to reviewers:*  the pre-commit and builder lint issues are addressed in #539.  I preemptively merged that PR into this branch, but please refer to #539 for details on those changes (and feel free to leave f/b on it in either PR - will address issues here).

2023-06-13 19:29 UTC, ebezzi commented on api/python/notebooks/experimental/highly_variable_genes.ipynb
> +    "This tutorial describes use of the `cellxgene_census.experimenta.pp` API for finding highly variable genes (HVGs) in the Census. The HVG algorithm implements the ranked normalized variance metho
```suggestion
    "This tutorial describes use of the `cellxgene_census.experiments.pp` API for finding highly variable genes (HVGs) in the Census. The HVG algorithm implements the ranked normalized variance method `seurat_v3` described in [`scanpy.pp.highly_variable_genes](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.highly_variable_genes.html#scanpy.pp.highly_variable_genes).\n",
```

2023-06-13 19:31 UTC, ebezzi commented on api/python/notebooks/experimental/highly_variable_genes.ipynb
> +    "Both functions accept common arguments to control ranking, with argument semantics matching the ScanPY API:\n",
```suggestion
    "Both functions accept common arguments to control ranking, with argument semantics matching the Scanpy API:\n",
```
This is the spelling used on their website

2023-06-13 19:31 UTC, ebezzi commented on api/python/notebooks/experimental/highly_variable_genes.ipynb
> +    "* `n_top_genes` - number of genes to rank\n",
```suggestion
    "* `n_top_genes` - number of genes to rank.\n",
```

2023-06-13 19:32 UTC, ebezzi commented on api/python/notebooks/experimental/highly_variable_genes.ipynb
> +    "This tutorial describes use of the `cellxgene_census.experimenta.pp` API for finding highly variable genes (HVGs) in the Census. The HVG algorithm implements the ranked normalized variance metho
```suggestion
    "This tutorial describes use of the `cellxgene_census.experimenta.pp` API for finding highly variable genes (HVGs) in the Census. The HVG algorithm implements the ranked normalized variance method `seurat_v3` described in [scanpy.pp.highly_variable_genes](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.highly_variable_genes.html#scanpy.pp.highly_variable_genes).\n",
```

2023-06-13 19:32 UTC, ebezzi commented on api/python/notebooks/experimental/highly_variable_genes.ipynb
> +    "This tutorial describes use of the `cellxgene_census.experimenta.pp` API for finding highly variable genes (HVGs) in the Census. The HVG algorithm implements the ranked normalized variance metho
Link is broken otherwise.

2023-06-13 19:41 UTC, ebezzi requested changes
A few typos/corrections but otherwise LGTM.

2023-06-14 00:31 UTC, ebezzi approved these changes

2023-06-14 17:32 UTC, pablo-gar approved these changes
Looks awesome! Thanks for cleaning up the symlinks (errors and removal of unused links)

2023-06-14 17:46 UTC, atolopko-czi approved these changes
LGTM

2023-06-14 18:04 UTC, merged