[r] more vignettes
chanzuckerberg/cellxgene-census pull request #680
Opened 2023-08-02 06:50 UTC by mlin

2023-08-02 17:34 UTC, pablo-gar requested changes

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +census <- cellxgene.census::open_soma()
```suggestion
library("Seurat")
census <- cellxgene.census::open_soma()
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +liver_seurat[1:5, 1:5]$RNA@data
Let's try to use the latest idoms

```suggestion
GetAssayData(liver_seurat[1:5, 1:5], slot = "data")
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +liver_seurat <- Seurat::SetAssayData(
```suggestion
liver_seurat <- SetAssayData(
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +  new.data = sweep(liver_seurat$RNA@data, 1, gene_lengths, "/")
```suggestion
  new.data = sweep(GetAssayData(liver_seurat, slot = "data"), 1, gene_lengths, "/")
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +liver_seurat[1:5, 1:5]$RNA@data
```suggestion
GetAssayData(liver_seurat[1:5, 1:5], slot = "data")
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +cells_per_gene <- Matrix::rowSums(liver_seurat$RNA@counts > 0)
```suggestion
cells_per_gene <- rowSums(GetAssayData(liver_seurat, slot = "counts") > 0)
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +genes_per_cell <- Matrix::colSums(liver_seurat$RNA@counts > 0)
```suggestion
genes_per_cell <- colSums(GetAssayData(liver_seurat, slot = "counts") > 0)
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +liver_seurat <- Seurat::NormalizeData(
```suggestion
liver_seurat <- NormalizeData(
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +liver_seurat <- Seurat::FindVariableFeatures(
```suggestion
liver_seurat <- FindVariableFeatures(
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +liver_seurat <- Seurat::ScaleData(liver_seurat, features = all.genes)
```suggestion
liver_seurat <- ScaleData(liver_seurat, features = all.genes)
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +  features = Seurat::VariableFeatures(object = liver_seurat)
```suggestion
  features = VariableFeatures(object = liver_seurat)
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +liver_seurat <- Seurat::FindNeighbors(liver_seurat, dims = 1:10)
Let's add a bit more entropy

```suggestion
liver_seurat <- FindNeighbors(liver_seurat, dims = 1:40)
```

2023-08-02 17:34 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/comp_bio_normalizing_full_gene_sequencing.Rmd
> +Seurat::DimPlot(liver_seurat, reduction = "umap", group.by = "cell_type")
```suggestion
DimPlot(liver_seurat, reduction = "umap", group.by = "cell_type")
```

2023-08-06 11:17 UTC, mlin commented
@pablo-gar added draft of compute_over_X, preview: https://rpubs.com/DNAmlin/1069339

this was fairly challenging to port, errata:

1. Omitted the online variance calculation for now (2nd of 3 sections).
    * Difficult to write as pure R in the vectorized way that you'd want to in order to run on it a large dataset (whereas the Python version benefits from numba).
    * Spent a few hours playing with inline Rcpp helpers, which was fun but I felt made the example way too involved in ways that didn't enhance exposition of the census/tiledbsoma API per se.
    * Suggest we leave this out for now and revisit with @bkmartinjr at a later time.
3. Some hoops jumped through in order avoid casting 64-bit `soma_joinid`s into R 32-bit integer, especially setting up data frames for joining. Familiar by now, but annoying.
4. (Previously mentioned) the indexer returning 0-based positions which we have to +1 into 1-based R vector positions.

(also applied all prior suggestions to comp_bio_normalizing_full_gene_sequencing, thanks!)

2023-08-14 21:11 UTC, pablo-gar requested changes
Some stylistic changes.

2023-08-14 21:11 UTC, pablo-gar commented on api/r/cellxgene.census/vignettes_/census_compute_over_X.Rmd
> +  n_cells_part$cell_id <- NULL
```suggestion
```

2023-08-17 16:44 UTC, pablo-gar approved these changes

2023-08-17 18:40 UTC, merged