Update R docs
chanzuckerberg/cellxgene-census pull request #684
Opened 2023-08-02 22:48 UTC by pablo-gar

Addresses #670 #668 #669

2023-08-03 20:32 UTC, mlin commented
Just one question, I noticed the new examples are generally using `a = b` rather than the more-frequently-seen `a <- b` for assignment. I don't feel strongly, but just checking it's intentional? (LGTM otherwise)

2023-08-03 20:40 UTC, atolopko-czi approved these changes
A few minor suggestions, but LGTM.  Disclaimer: Did not "test" the R instructions and haven't seen the rendered docs.

2023-08-03 20:40 UTC, atolopko-czi commented on api/r/cellxgene.census/README.md
> +From an R session, first install `tiledb` from R-Universe, the latest release in CRAN is not yet available.
```suggestion
From an R session, first install `tiledb` from R-Universe, as the latest release in CRAN is not yet available.
```

2023-08-03 20:40 UTC, atolopko-czi commented on api/r/cellxgene.census/README.md
> +The following creates an `Seurat` object on-demand with all sympathetic neurons in Census and filtering only for the genes `ENSG00000161798`, `ENSG00000188229`.
```suggestion
The following creates a `Seurat` object on-demand with all sympathetic neurons in Census and filtering only for the genes `ENSG00000161798`, `ENSG00000188229`.
```

2023-08-03 20:40 UTC, atolopko-czi commented on api/r/cellxgene.census/README.md
> +This is the documentation for the R package `cellxgene.census` which is part of Census by CZ CELLxGENE Discover. For full details on Census data and capabilities please go to the [main Census site](h
Maybe this?
```suggestion
This is the documentation for the R package `cellxgene.census` which is part of CZ CELLxGENE Discover Census. For full details on Census data and capabilities please go to the [main Census site](https://chanzuckerberg.github.io/cellxgene-census/).  
```

2023-08-03 20:40 UTC, atolopko-czi commented on docs/cellxgene_census_docsite_installation.md
> +From an R session, first install `tiledb` from R-Universe, the latest release in CRAN is not yet available.
```suggestion
From an R session, first install `tiledb` from R-Universe, as the latest release in CRAN is not yet available.
```

2023-08-03 20:40 UTC, atolopko-czi commented on api/r/cellxgene.census/README.md
> +From an R session, first install `tiledb` from R-Universe, the latest release in CRAN is not yet available.
Since this is repeated in online docs, checking that you definitely want to repeat it here rather than linking out? It's not unreasonable, as is.

2023-08-03 20:40 UTC, atolopko-czi commented on docs/cellxgene_census_docsite_quick_start.md
> +The following creates an Seurat object on-demand with a smaller set of cells  and filtering only the genes `ENSG00000161798`, `ENSG00000188229`.
```suggestion
The following creates a Seurat object on-demand with a smaller set of cells and filtering only the genes `ENSG00000161798`, `ENSG00000188229`.
```

2023-08-03 20:40 UTC, atolopko-czi commented on docs/cellxgene_census_docsite_quick_start.md
> +# Continued below
necessary?

2023-08-04 09:49 UTC, mlin requested changes

2023-08-04 09:49 UTC, mlin commented on api/r/cellxgene.census/README.md
> +  repos=c('https://tiledb-inc.r-universe.dev','https://cloud.r-project.org')
```suggestion
  repos=c('https://chanzuckerberg.r-universe.dev','https://cloud.r-project.org') 
```

2023-08-04 17:47 UTC, pablo-gar commented on api/r/cellxgene.census/README.md
> +  repos=c('https://tiledb-inc.r-universe.dev','https://cloud.r-project.org')
Done!

2023-08-04 18:00 UTC, mlin approved these changes

2023-08-04 20:26 UTC, merged