[r] test first-time R package installation
chanzuckerberg/cellxgene-census pull request #687
Opened 2023-08-04 09:45 UTC by mlin

Adding a Dockerfile and script to test our instructions for installing `cellxgene.census` and `tiledbsoma`. For now it's to run manually. In a follow-up we could run it as a GitHub workflow also with a macOS analog.

2023-08-04 13:05 UTC, atolopko-czi approved these changes
LGTM and thanks for adding! Only thought is that install.R could return a non-zero exit code on failure.

2023-08-04 18:06 UTC, pablo-gar approved these changes

2023-08-04 19:52 UTC, pablo-gar requested changes

2023-08-04 19:52 UTC, pablo-gar commented on api/r/cellxgene.census/tests/installation/install.R
> +  version = "0.20.2",
```suggestion
  version = "0.20.3",
```

2023-08-14 20:20 UTC, pablo-gar approved these changes

2023-08-15 04:00 UTC, merged