[docs] add `no-sign-request` flag to model download in tutorials
chanzuckerberg/cellxgene-census pull request #956
Opened 2024-01-25 18:48 UTC by pablo-gar

2024-01-25 19:12 UTC, atolopko-czi approved these changes

2024-01-25 19:15 UTC, ebezzi requested changes

2024-01-25 19:15 UTC, ebezzi commented on api/python/notebooks/analysis_demo/comp_bio_scvi_model_use.ipynb
> +    "!aws s3 sync --no-sign-request  --no-progress --only-show-errors s3://cellxgene-contrib-public/models/scvi/2023-12-15/homo_sapiens/model.pt 2023-12-15-scvi-homo-sapiens/scvi.model/"
I think you need to keep `cp` here. I tried and `sync` doesn't work since it's trying to copy a specific file.

2024-01-26 17:23 UTC, pablo-gar commented on api/python/notebooks/analysis_demo/comp_bio_scvi_model_use.ipynb
> +    "!aws s3 sync --no-sign-request  --no-progress --only-show-errors s3://cellxgene-contrib-public/models/scvi/2023-12-15/homo_sapiens/model.pt 2023-12-15-scvi-homo-sapiens/scvi.model/"
```suggestion
    "!aws s3 cp --no-sign-request  --no-progress --only-show-errors s3://cellxgene-contrib-public/models/scvi/2023-12-15/homo_sapiens/model.pt 2023-12-15-scvi-homo-sapiens/scvi.model/"
```

2024-02-01 18:09 UTC, ebezzi approved these changes

2024-02-01 18:41 UTC, merged